device: cuda:0
epochs: 100
model:
  args: null
  load_from: experiments/010-20230911-13-10-08/06.pt
  type: UNet
optimizer:
  args:
    lr: 0.001
  type: Adam
train_dataset:
  args:
    batch_size: 4
    shuffle: True
    num_workers: 0
  transform: BaseAugmentation
  loader_args: null
  type: FisheyeDataset
val_dataset:
  args:
    batch_size: 2
    shuffle: False
    num_workers: 0
  transform: BaseAugmentation
  loader_args: null
  type: FisheyeDataset
wandb:
  run_name: customdata_with_rousseau
  use: true