# experiment setup
device: cuda:0
epochs: 100
expr_save_path: ./experiments2
earlystop: 
  patience: 10
  monitor: val_loss # val_loss(default), val_metric
wandb:
  run_name: test_baseline
  use: True
seed: 42

# model
model:
  type: Unet
  lib: smp # torch(base), smp
  args: 
    encoder_name: resnet34
    encoder_weights: imagenet
    in_channels: 3
    classes: 13
  load_from: null

# optimizer
optimizer:
  type: Adam
  args:
    lr: 0.001

# runner
runner:
  train: base_trainer
  val: validator 

# dataset
train_dataset:
  type: FisheyeDataset
  path: ./data/train_source.csv
  args:
    infer: False
  transform: 
    type: BaseAugmentation
    args:
      resize: 224
      p: 0.5
  loader_args:
    batch_size: 4
    shuffle: True
    num_workers: 0
val_dataset:
- type: FisheyeDataset
  path: ./data/val_source.csv
  args:
    infer: False
  transform: 
    type: BaseAugmentation
    args:
      resize: 224
      p: 1.0
  loader_args:
    batch_size: 2
    shuffle: False
    num_workers: 0
