device: cuda:0
epochs: 100
model:
  lib: smp
  args: 
    encoder_name: resnet34
    encoder_weights: imagenet
    in_channels: 3
    classes: 13
  load_from: null
  type: Unet
optimizer:
  args:
    lr: 0.001
  type: Adam
train_dataset:
  args:
    batch_size: 4
    shuffle: True
    num_workers: 0
  transform: 
    type: FisheyeAugmentation
    args:
      resize: 224
      focal_ratio: 0.125
      center_x_ratio: 0.5
      center_y_ratio: 0.5
      p: 0.5
  loader_args: null
  type: FisheyeDataset
val_dataset:
- args:
    batch_size: 2
    shuffle: False
    num_workers: 0
  transform: 
    type: BaseAugmentation
    args:
      resize: 224
      p: 1.0
  loader_args: null
  type: FisheyeDataset
- args:
    batch_size: 2
    shuffle: False
    num_workers: 0
  transform: 
    type: FisheyeAugmentation
    args:
      resize: 224
      focal_ratio: 0.125
      center_x_ratio: 0.5
      center_y_ratio: 0.5
      p: 1.0
  loader_args: null
  type: FisheyeDataset
wandb:
  run_name: smptest
  use: true