# experiment setup
device: cuda:0
epochs: 100
expr_save_path: ./experiments
earlystop: 
  patience: 50
  monitor: val_metric # val_loss(default), val_metric
wandb:
  run_name: SegFormer_AdaptSeg
  use: True
amp: True
seed: 42

# model
model:
  type: SegFormer
  lib: torch # torch(base), smp
  args: 
    num_classes: 13
    pretrained: True
  load_from: null

# optimizer
optimizer:
  type: SGD
  args:
    lr: 2.5e-4
    momentum: 0.9
    weight_decay: 0.0005

# runner
runner:
  train: adaptseg_segformer_trainer
  val: validator 


# dataset
train_dataset:
  type: FisheyeDataset
  path: ./data/train_source.csv
  args:
    infer: False
  transform: 
    type: BaseAugmentation
    args:
      resize: (540, 960)
      p: 1.0
  loader_args:
    batch_size: 2
    shuffle: True
    num_workers: 4
val_dataset:
- type: FisheyeDataset
  path: ./data/val_source.csv
  args:
    infer: False
  transform: 
    type: BaseAugmentation
    args:
      resize: (540, 960)
      p: 1.0
  loader_args:
    batch_size: 4
    shuffle: False
    num_workers: 4
