device: cuda:0
epochs: 100
expr_save_path: ./experiments2
earlystop: 
  patience: 10
  monitor: val_loss # val_loss(default), val_metric
model:
  lib: smp # torch(base), smp
  args: 
    encoder_name: resnet34
    encoder_weights: imagenet
    in_channels: 3
    classes: 13
  load_from: null
  type: Unet
optimizer:
  args:
    lr: 0.001
  type: Adam
train_dataset:
  path: ./data/train_source.csv
  args:
    infer: False
  transform: 
    type: BaseAugmentation
    args:
      resize: 224
      p: 0.5
  loader_args:
    batch_size: 4
    shuffle: True
    num_workers: 0
  type: FisheyeDataset
val_dataset:
- path: ./data/val_source.csv
  args:
    infer: False
  transform: 
    type: BaseAugmentation
    args:
      resize: 224
      p: 1.0
  loader_args:
    batch_size: 2
    shuffle: False
    num_workers: 0
  type: FisheyeDataset
wandb:
  run_name: test_baseline
  use: True