# experiment setup
device: cuda:0
epochs: 100
expr_save_path: ./experiments
earlystop: 
  patience: 10
  monitor: val_loss # val_loss(default), val_metric
wandb:
  run_name: adaptseg_test
  use: False
seed: 42

# model
model:
  type: DeeplabMulti
  lib: torch # torch(base), smp
  args: 
    num_classes: 13
    multi: True
    # encoder_name: resnet101
    # encoder_weights: imagenet
    # in_channels: 3
    # classes: 13
  load_from: null

# optimizer
optimizer:
  type: SGD
  args:
    lr: 2.5e-4
    momentum: 0.9
    weight_decay: 0.0005

# runner
runner:
  train: adaptseg_trainer
  val: validator 

# dataset
train_dataset:
  type: FisheyeDataset
  path: ./data/train_source.csv
  args:
    infer: False
  transform: 
    type: BaseAugmentation
    args:
      resize: (448, 448)
      p: 1.0
  loader_args:
    batch_size: 4
    shuffle: True
    num_workers: 4
val_dataset:
- type: FisheyeDataset
  path: ./data/val_source.csv
  args:
    infer: False
  transform: 
    type: BaseAugmentation
    args:
      resize: (448, 448)
      p: 1.0
  loader_args:
    batch_size: 4
    shuffle: False
    num_workers: 0
