# experiment setup
device: cuda:0
epochs: 100
expr_save_path: ./experiments
earlystop: 
  patience: 10
  monitor: val_metric # val_loss(default), val_metric
wandb:
  run_name: customdeeplabv2_pretrained_contd
  use: True
seed: 42

# model
model:
  type: DeeplabMulti
  lib: torch # torch(base), smp
  args: 
    num_classes: 13
    pretrained: True
  load_from: ./experiments/022_20230918_084033_customdeeplabv2_pretrained/23.pt

# optimizer
optimizer:
  type: Adam
  args:
    lr: 0.0002

# runner
runner:
  train: base_trainer
  val: validator 

# dataset
train_dataset:
  type: FisheyeDataset
  path: ./data/train_source.csv
  args:
    infer: False
  transform: 
    type: BaseAugmentation
    args:
      resize: (448, 448)
      p: 1.0
  loader_args:
    batch_size: 4
    shuffle: True
    num_workers: 4
val_dataset:
- type: FisheyeDataset
  path: ./data/val_source.csv
  args:
    infer: False
  transform: 
    type: BaseAugmentation
    args:
      resize: (448, 448)
      p: 1.0
  loader_args:
    batch_size: 4
    shuffle: False
    num_workers: 0
